Help on module _msi:

NAME
    _msi - Documentation

CLASSES
    builtins.Exception(builtins.BaseException)
        MSIError
    
    class MSIError(builtins.Exception)
     |  Common base class for all non-exit exceptions.
     |  
     |  Method resolution order:
     |      MSIError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
     |  
     |  Data descriptors defined here:
     |  
     |  __weakref__
     |      list of weak references to the object (if defined)
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.Exception:
     |  
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |  
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.Exception:
     |  
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |  
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.BaseException:
     |  
     |  __delattr__(self, name, /)
     |      Implement delattr(self, name).
     |  
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |  
     |  __reduce__(...)
     |      Helper for pickle.
     |  
     |  __repr__(self, /)
     |      Return repr(self).
     |  
     |  __setattr__(self, name, value, /)
     |      Implement setattr(self, name, value).
     |  
     |  __setstate__(...)
     |  
     |  __str__(self, /)
     |      Return str(self).
     |  
     |  with_traceback(...)
     |      Exception.with_traceback(tb) --
     |      set self.__traceback__ to tb and return self.
     |  
     |  ----------------------------------------------------------------------
     |  Data descriptors inherited from builtins.BaseException:
     |  
     |  __cause__
     |      exception cause
     |  
     |  __context__
     |      exception context
     |  
     |  __dict__
     |  
     |  __suppress_context__
     |  
     |  __traceback__
     |  
     |  args

FUNCTIONS
    CreateRecord(...)
        OpenDatabase(name, flags) -> dbobj
        Wraps MsiCreateRecord
    
    FCICreate(...)
        fcicreate(cabname,files) -> None
    
    OpenDatabase(...)
        OpenDatabase(name, flags) -> dbobj
        Wraps MsiOpenDatabase
    
    UuidCreate(...)
        UuidCreate() -> string

DATA
    MSICOLINFO_NAMES = 0
    MSICOLINFO_TYPES = 1
    MSIDBOPEN_CREATE = 3
    MSIDBOPEN_CREATEDIRECT = 4
    MSIDBOPEN_DIRECT = 2
    MSIDBOPEN_PATCHFILE = 32
    MSIDBOPEN_READONLY = 0
    MSIDBOPEN_TRANSACT = 1
    MSIMODIFY_ASSIGN = 3
    MSIMODIFY_DELETE = 6
    MSIMODIFY_INSERT = 1
    MSIMODIFY_INSERT_TEMPORARY = 7
    MSIMODIFY_MERGE = 5
    MSIMODIFY_REFRESH = 0
    MSIMODIFY_REPLACE = 4
    MSIMODIFY_SEEK = -1
    MSIMODIFY_UPDATE = 2
    MSIMODIFY_VALIDATE = 8
    MSIMODIFY_VALIDATE_DELETE = 11
    MSIMODIFY_VALIDATE_FIELD = 10
    MSIMODIFY_VALIDATE_NEW = 9
    PID_APPNAME = 18
    PID_AUTHOR = 4
    PID_CHARCOUNT = 16
    PID_CODEPAGE = 1
    PID_COMMENTS = 6
    PID_CREATE_DTM = 12
    PID_KEYWORDS = 5
    PID_LASTAUTHOR = 8
    PID_LASTPRINTED = 11
    PID_LASTSAVE_DTM = 13
    PID_PAGECOUNT = 14
    PID_REVNUMBER = 9
    PID_SECURITY = 19
    PID_SUBJECT = 3
    PID_TEMPLATE = 7
    PID_TITLE = 2
    PID_WORDCOUNT = 15

FILE
    c:\program files\python37\dlls\_msi.pyd


